# Dynamic configuration file for Traefik
# This file is watched for changes

# TLS Options
tls:
  options:
    default:
      sslProtocols:
        - "TLSv1.2"
        - "TLSv1.3"
      minVersion: "VersionTLS12"

# HTTP Middlewares
http:
  middlewares:
    # Security headers
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customRequestHeaders:
          X-Forwarded-Proto: "https"

    # Basic auth (uncomment and configure if needed)
    # basic-auth:
    #   basicAuth:
    #     users:
    #       - "admin:$2y$10$..." # Use htpasswd to generate

    # Rate limiting
    rate-limit:
      rateLimit:
        burst: 100
        average: 50