api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@example.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: http

# Global redirect to https
http:
  routers:
    http-catchall:
      rule: "hostregexp(`{host:.+}`)"
      entryPoints:
        - http
      middlewares:
        - redirect-to-https
      service: api@internal
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true