---
- name: Install Docker Only
  hosts: docker_hosts
  become: true
  gather_facts: true
  
  roles:
    - role: common
      tags: [common]
    - role: docker_install
      tags: [docker, install]

  post_tasks:
    - name: Verify Docker installation
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Verify Docker Compose installation  
      ansible.builtin.command: docker compose version
      register: compose_version
      changed_when: false

    - name: Display versions
      ansible.builtin.debug:
        msg:
          - "{{ docker_version.stdout }}"
          - "{{ compose_version.stdout }}"