---
- name: Setup Ubuntu System and Deploy Homelab Stack
  hosts: "{{ target_env | default('production') }}"
  become: true
  gather_facts: true
  
  # Caricare le variabili sensibili da file separato
  vars_files:
    - ../secrets.yml
  
  # Integrare la configurazione del sistema Ubuntu prima del deploy
  pre_tasks:
    - name: Display deployment information
      debug:
        msg:
          - "Deploying to environment: {{ env_name }}"
          - "Target host: {{ inventory_hostname }}"
          - "Domain: {{ domain_name }}"
          - "Traefik log level: {{ traefik_log_level }}"
    
    - name: Include Ubuntu system configuration
      include_role:
        name: ubuntu-system-config
    
    - name: Install Docker
      include_role:
        name: docker_install
        
    - name: Create application directory
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create Traefik configuration directory
      ansible.builtin.file:
        path: "{{ app_directory }}/traefik"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Generate Traefik configuration from template
      ansible.builtin.template:
        src: traefik.yml.j2
        dest: "{{ app_directory }}/traefik/traefik.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Generate Traefik dynamic configuration from template
      ansible.builtin.template:
        src: dynamic.yml.j2
        dest: "{{ app_directory }}/traefik/dynamic.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Create Traefik environment file with Cloudflare credentials
      ansible.builtin.copy:
        dest: "{{ app_directory }}/traefik/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
        content: |
          # Cloudflare configuration for Let's Encrypt DNS challenge
          CLOUDFLARE_EMAIL={{ cloudflare_email }}
          CLOUDFLARE_DNS_API_TOKEN={{ cloudflare_api_token }}
      when: ssl_enabled | default(false) | bool

    - name: Create empty Traefik environment file for non-SSL deployments
      ansible.builtin.copy:
        dest: "{{ app_directory }}/traefik/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
        content: |
          # No SSL configuration needed for development
          # Add any other environment variables here if needed
      when: not (ssl_enabled | default(false) | bool)

    - name: Create unbound configuration directory
      ansible.builtin.file:
        path: "{{ app_directory }}/unbound"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create unbound configuration file
      ansible.builtin.copy:
        dest: "{{ app_directory }}/unbound/unbound.conf"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
        content: |
          server:
              verbosity: 0
              interface: 0.0.0.0
              port: 53
              do-ip4: yes
              do-ip6: no
              do-udp: yes
              do-tcp: yes
              
              # Allow queries from anywhere (for Docker container)
              access-control: 0.0.0.0/0 allow
              
              # Trust glue only if it is within the servers authority
              harden-glue: yes
              
              # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
              harden-dnssec-stripped: yes
              
              # Don't use Capitalization randomization as it known to cause DNSSEC issues
              use-caps-for-id: no
              
              # Reduce EDNS reassembly buffer size.
              edns-buffer-size: 1232
              
              # Perform prefetching of close to expired message cache entries
              prefetch: yes
              
              # One thread should be sufficient
              num-threads: 1
              
              # Ensure kernel buffer is large enough
              so-rcvbuf: 1m
              
              # Ensure privacy of local IP ranges
              private-address: 192.168.0.0/16
              private-address: 169.254.0.0/16
              private-address: 172.16.0.0/12
              private-address: 10.0.0.0/8
              private-address: fd00::/8
              private-address: fe80::/10
        
  vars:
    compose_project_name: homelab
    app_directory: /opt/homelab
    network_subnet: "172.21.0.0/16"
    
    # Create necessary directories and volumes
    compose_volumes:
      - name: traefik_data
        driver: local
      - name: pihole_config
        driver: local
      - name: pihole_dnsmasq
        driver: local
      - name: uptime_kuma_data
        driver: local

    compose_services: "{{ homelab_services | selectattr('enabled', 'equalto', true) | list }}"
    
    # Define all possible services with conditional deployment
    homelab_services:
      - name: traefik
        enabled: "{{ deploy_traefik | default(true) }}"
        image: traefik:v3.0
        container_name: traefik
        restart: "{{ restart_policy | default('unless-stopped') }}"
        ports:
          - "80:80"
          - "443:443"
          - "8081:8080"  # Traefik dashboard
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "traefik_data:/data"
          - "{{ app_directory }}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
          - "{{ app_directory }}/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
        env_file:
          - "{{ app_directory }}/traefik/.env"
        security_opt:
          - "no-new-privileges:true"
        labels:
          traefik.enable: "true"
          traefik.http.routers.traefik-dashboard.rule: "Host(`traefik.{{ domain_name }}`)"
          traefik.http.routers.traefik-dashboard.entrypoints: "{{ 'https' if ssl_enabled | default(false) else 'http' }}"
          traefik.http.routers.traefik-dashboard.service: "api@internal"
          traefik.http.routers.traefik-dashboard.tls: "{{ 'true' if ssl_enabled | default(false) else 'false' }}"
          traefik.http.routers.traefik-dashboard.tls.certresolver: "{{ 'letsencrypt' if ssl_enabled | default(false) else '' }}"
          traefik.http.services.traefik-dashboard.loadbalancer.server.port: "8080"

      - name: unbound
        enabled: "{{ deploy_unbound | default(true) }}"
        image: mvance/unbound:latest
        container_name: unbound
        restart: "{{ restart_policy | default('unless-stopped') }}"
        ports:
          - "5353:53/tcp"
          - "5353:53/udp"
        volumes:
          - "{{ app_directory }}/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro"
        cap_add:
          - "NET_BIND_SERVICE"
        security_opt:
          - "no-new-privileges:true"
        labels:
          traefik.enable: "false"

      - name: pihole
        enabled: "{{ deploy_pihole | default(true) }}"
        image: pihole/pihole:latest
        container_name: pihole
        restart: "{{ restart_policy | default('unless-stopped') }}"
        ports:
          - "53:53/tcp"
          - "53:53/udp"
        volumes:
          - "pihole_config:/etc/pihole"
          - "pihole_dnsmasq:/etc/dnsmasq.d"
        environment:
          TZ: "Europe/Rome"
          FTLCONF_webserver_api_password: "{{ pihole_webpassword }}"
          FTLCONF_dns_upstreams: "unbound#53"
          FTLCONF_dns_listeningMode: "all"
          FTLCONF_dns_dnssec: "true"
          FTLCONF_webserver_cors_hosts: "pihole.{{ domain_name }}"
          VIRTUAL_HOST: "pihole.{{ domain_name }}"
        depends_on:
          - unbound
        security_opt:
          - "no-new-privileges:true"
        cap_add:
          - "NET_BIND_SERVICE"
          - "NET_ADMIN"
        labels:
          traefik.enable: "true"
          traefik.http.routers.pihole.rule: "Host(`pihole.{{ domain_name }}`)"
          traefik.http.routers.pihole.entrypoints: "{{ 'https' if ssl_enabled | default(false) else 'http' }}"
          traefik.http.routers.pihole.tls: "{{ 'true' if ssl_enabled | default(false) else 'false' }}"
          traefik.http.routers.pihole.tls.certresolver: "{{ 'letsencrypt' if ssl_enabled | default(false) else '' }}"
          traefik.http.services.pihole.loadbalancer.server.port: "80"

      - name: uptime-kuma
        enabled: "{{ deploy_uptime_kuma | default(true) }}"
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        restart: "{{ restart_policy | default('unless-stopped') }}"
        volumes:
          - "uptime_kuma_data:/app/data"
        environment:
          UPTIME_KUMA_PORT: "3001"
        security_opt:
          - "no-new-privileges:true"
        labels:
          traefik.enable: "true"
          traefik.http.routers.uptime-kuma.rule: "Host(`uptime.{{ domain_name }}`)"
          traefik.http.routers.uptime-kuma.entrypoints: "{{ 'https' if ssl_enabled | default(false) else 'http' }}"
          traefik.http.routers.uptime-kuma.tls: "{{ 'true' if ssl_enabled | default(false) else 'false' }}"
          traefik.http.routers.uptime-kuma.tls.certresolver: "{{ 'letsencrypt' if ssl_enabled | default(false) else '' }}"
          traefik.http.services.uptime-kuma.loadbalancer.server.port: "3001"

  roles:
    - role: docker_compose
      tags: [compose, deploy]

  post_tasks:
    - name: Display service URLs
      ansible.builtin.debug:
        msg:
          - "🎯 {{ env_name | upper }} ENVIRONMENT DEPLOYED"
          - "🌐 Domain: {{ domain_name }}"
          - ""
          - "🚀 Services Available:"
          - "  • Traefik Dashboard: http://{{ ansible_host }}:8081"
          - "  • Traefik Dashboard (via proxy): {{ 'https' if ssl_enabled | default(false) else 'http' }}://traefik.{{ domain_name }}"
          - "  • Uptime Kuma: {{ 'https' if ssl_enabled | default(false) else 'http' }}://uptime.{{ domain_name }}"
          - ""

    - name: Display Pi-hole information
      debug:
        msg:
          - "  • Pi-hole Admin: {{ 'https' if ssl_enabled | default(false) else 'http' }}://pihole.{{ domain_name }}"
          - ""
          - "🔧 DNS Configuration:"
          - "  Primary DNS: {{ ansible_host }}"
          - "  Pi-hole Web Password: {{ pihole_webpassword }}"
          - ""
          - "📋 To configure clients to use Pi-hole DNS:"
          - "  Set DNS server to {{ ansible_host }} in your router or device settings"
      when: deploy_pihole | default(true)

    - name: Display Proxmox information
      debug:
        msg:
          - "  • Proxmox VE: https://pve.{{ domain_name }}"
      when: deploy_proxmox_routes | default(false)

    - name: Display SSL information
      debug:
        msg:
          - "🔒 SSL/TLS Status: ENABLED with Let's Encrypt certificates"
          - "   All services accessible via HTTPS with valid certificates"
      when: ssl_enabled | default(false)

    - name: Display development notice
      debug:
        msg:
          - "ℹ️  Development environment - Pi-hole/Unbound not deployed"
          - "   This environment is optimized for testing and development"
      when: 
        - env_name == "development"
        - not (deploy_pihole | default(true))