---
- name: Quick Proxmox VE Update (No Reboot)
  hosts: proxmox
  become: true
  gather_facts: true

  vars_files:
    - ../secrets.yml

  tasks:
    - name: Display quick update information
      ansible.builtin.debug:
        msg:
          - "⚡ Quick Proxmox VE Update (No Reboot)"
          - "Target host: {{ inventory_hostname }}"
          - "Current time: {{ ansible_date_time.iso8601 }}"

    - name: Check current Proxmox version
      ansible.builtin.shell: pveversion
      register: proxmox_current_version
      changed_when: false

    - name: Display current version
      ansible.builtin.debug:
        msg: "Current Proxmox version: {{ proxmox_current_version.stdout }}"

    - name: Configure no-subscription repository
      ansible.builtin.apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
        filename: pve-no-subscription
        state: present

    - name: Remove enterprise repository (if no subscription)
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0

    - name: Check for available updates
      ansible.builtin.shell: |
        apt list --upgradable 2>/dev/null | grep -v "WARNING" | wc -l
      register: available_updates
      changed_when: false

    - name: Display available updates
      ansible.builtin.debug:
        msg: "Available updates: {{ (available_updates.stdout | int) - 1 }} packages"

    - name: Perform package updates (excluding kernel)
      ansible.builtin.apt:
        upgrade: true
        force_apt_get: true
        autoremove: true
        autoclean: true
      when: (available_updates.stdout | int) > 1

    - name: Check updated Proxmox version
      ansible.builtin.shell: pveversion
      register: proxmox_new_version
      changed_when: false

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Display update summary
      ansible.builtin.debug:
        msg:
          - "⚡ QUICK UPDATE COMPLETED"
          - "Host: {{ inventory_hostname }}"
          - "Previous version: {{ proxmox_current_version.stdout }}"
          - "Current version: {{ proxmox_new_version.stdout }}"
          - "Reboot required: {{ reboot_required.stat.exists }}"
          - "{% if reboot_required.stat.exists %}⚠️  REBOOT REQUIRED - Run full update playbook{% endif %}"