---
# Production Environment Configuration
environment: production
compose_project_name: myapp_prod
app_directory: /opt/myapp
network_subnet: "172.30.0.0/16"

# Production settings
compose_pull_policy: always
compose_recreate: auto

# Production security-focused configuration
compose_services:
  - name: web
    image: "nginx:1.25-alpine"
    user: "101:101"  # nginx user
    read_only: true
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=50m
      - /var/run:noexec,nosuid,size=10m
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:8080"
    environment:
      ENVIRONMENT: production
    volumes:
      - "{{ app_directory }}/html:/usr/share/nginx/html:ro"
      - "{{ app_directory }}/nginx.conf:/etc/nginx/nginx.conf:ro"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Environment variables for .env file
compose_environment:
  APP_ENV: production
  DEBUG: "false"
  LOG_LEVEL: warning